### ISSUE TITLE
Blood of the Martyr is missing Synergy info with Book of Belial

### ISSUE THREAD

**Issue by wofsauge** [vlopp/IsaacItemBrowser#1]
Source:
https://bindingofisaacrebirth.gamepedia.com/Blood_of_the_Martyr

**Comment by vlopp** [comment]
The data is automatically scraped from the wiki during build time. The last build was done quite a while ago.

I will rebuild tomorrow and perhaps shedule further rebuilds in intervals somehow.

Thanks for the notice.

**Comment by vlopp** [comment]
Fixed.
