### ISSUE TITLE
Steven Description is wrong

### ISSUE THREAD

**Issue by wofsauge** [vlopp/IsaacItemBrowser#3]
It displays the description for "Steven" the Boss, not the item.
The Wikilink is also wrong.

Correct link:
https://bindingofisaacrebirth.gamepedia.com/Steven_(Item)

**Comment by vlopp** [comment]
Thanks, there still are a few naming conflicts that I haven't caught yet.

The conflicts are resolved in `gameDataExtractor/src/parseItem.ts`
Feel free to create a pull request, if you wish to fix it yourself. Otherwise, I'll fix it myself soon.

**Comment by vlopp** [comment]
Fixed.
