### ISSUE TITLE
Little C.H.A.D description is wrong

### ISSUE THREAD

**Issue by wofsauge** [vlopp/IsaacItemBrowser#4]
It says "Drops a half red heart every two rooms." but its actually every three rooms.

**Comment by vlopp** [comment]
The data is automatically scraped from the wiki during build time. The last build was done quite a while ago.

I will rebuild tomorrow and perhaps shedule further rebuilds in intervals somehow.

Thanks for the notice.

**Comment by vlopp** [comment]
Fixed.
