### ISSUE TITLE
Dead Bird damage is wrong

### ISSUE THREAD

**Issue by wofsauge** [vlopp/IsaacItemBrowser#6]
The Damage was 2 per tick or 4 per second in the wiki, but its actually 20 and 40. I fixed the wiki so you can do the next update ;)

**Comment by wofsauge** [comment]
Same for Holy Water

**Comment by vlopp** [comment]
> The Damage was 2 per tick or 4 per second in the wiki, but its actually 20 and 40. I fixed the wiki so you can do the next update ;)

This is the description I see on the wiki currently: "Taking damage summons a familiar that chases enemies for the remainder of the current room, **dealing 2 damage per tick or 4 damage per second.**"

Tell me once it's updated. I have no idea how the wiki works, perhaps it needs a while to show changes publicly.

**Comment by wofsauge** [comment]
Someone reverted the change back. i fixed that now.

**Comment by vlopp** [comment]
Fixed.
